### ISSUE TITLE
Begin prepping 5.4 release testing

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/mission-control-dashboard#24]
```[tasklist]
### Tasks
- [ ] https://github.com/patternfly/patternfly-react/issues/10404
- [ ] https://github.com/patternfly/patternfly-react/issues/10403
- [ ] https://github.com/patternfly/patternfly-react/issues/10402
- [x] determine code freeze date with Coker/Titani given what's left to do
- [x] Identify/document which extensions are being released
- [x] Identify and prep (in pf-release channel) product testers
- [x] verify extensions are all building with pre-prereleases in mission control dashboard
- [ ] https://github.com/patternfly/patternfly-org/issues/4114
```
